server:
  port: 8088
spring:
  rabbitmq:
    host: 192.168.110.228
    port: 5672
    username: admin
    password: 123
    publisher-confirms: true # 开启发布确认 默认false 不开启
    publisher-returns: true # 开启消息退回 默认false 不开启